config/routes.rb
Rails.application.routes.draw do

  root 'events#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :events, only: [:new, :create, :show, :index, :destroy]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event 
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator,    class_name: "User"
  has_many :attendances,  dependent: :destroy
  has_many :attendees,    through: :attendances,
                          source: :user
  validates :name, :description, :location, presence: true
  validate :not_in_past
  scope :future, -> { where("date_time > ?", Time.now) }
  scope :past, -> { where("date_time < ?", Time.now) }
  accepts_nested_attributes_for :attendances



  private
  def not_in_past
    if self.date_time.past?
      errors.add(:date, 'not in past')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, foreign_key: "creator_id",
                            class_name: "Event",
                            dependent: :destroy

  has_many :attendances, dependent: :destroy
  has_many :attended_events, through: :attendances,
                            source: :event

  has_secure_password
  validates :name, presence: true,
                  length: { in: 2..15 }

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false }

  validates :password, length: { minimum: 5 }, allow_nil: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def not_logged_in
    if logged_in?
      flash[:danger] = "Please log out to create a new user."
      redirect_to root_path
    end
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_path
    end
  end

end

app/controllers/events_controller.rb
require 'pry'

class EventsController < ApplicationController
  before_action :logged_in_user, only: [:new]
  before_action :user_is_creator, only: [:destroy]

  def new
    @event = Event.new
    @event.attendances.build
  end

  def create
    @event = current_user.created_events.new(event_params)
    if @event.save
      add_attendees
      flash[:success] = "Event created!"
      redirect_to @event
    else
      flash.now[:danger] = "Invalid information."
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @upcoming_events = Event.future
    @past_events = Event.past
  end

  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event deleted."
    redirect_to root_path
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :location, :date_time)
  end

  def add_attendees
    # binding.pry
    invited_list = params.permit(:event => { attendees: [:names] }).to_h[:event][:attendees][:names]
    # invited_list = params.permit(event: :attendees).to_h[:event][:attendees].split(" ")
    invited_list.split(" ").each do |a|
      u = User.find_by(name: a)
      next if u.nil?
      @event.attendees << u
      # Attendance.new(user_id: u.id, event_id: @event.id).save
    end
  end

  def user_is_creator
    creator = Event.find(params[:id]).creator
    unless current_user == creator
      flash[:danger] = "Only the host can delete an event!"
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login user
      flash[:success] = "Welcome back, #{user.name}!"
      redirect_to user
    else
      flash.now[:danger] = "Invalid login information."
      render 'new'
    end
  end

  def destroy
    log_out
    flash[:success] = "Logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_logged_in, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      flash[:success] = "Welcome to Private Events!"
      redirect_to @user
    else
      flash.now[:danger] = "Oh no, invalid information!"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">Private Events</h1>
      <% if logged_in? %>
        <%= link_to "Create Event", new_event_url, class: "btn btn-primary btn-xl rounded-pill mt-5"%>
      <% else %>
        <%= link_to "Sign Up", new_user_url, class: "btn btn-primary btn-xl rounded-pill mt-5"%>
      <% end %>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>

<div class="container" id="events-index">
  <div class="text-center text-black">
    <br><h1 class="masthead-heading mb-0">Upcoming Events</h1><br>
  </div>
  <% @upcoming_events.each do |event| %>
  <div class="row">
    <%= render 'layouts/event', :event => event  %>
  </div>
  <% end %>
</div>

<div class="container" id="events-index">
  <div class="text-center text-black">
    <br><h1 class="masthead-heading mb-0">Past Events</h1><br>
  </div>
  <% @past_events.each do |event| %>
  <div class="row">
    <%= render 'layouts/event', :event => event  %>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<% provide(:title, "New Event") %>
    <div class="row" id="add-top-padding">
      <div class="col-md-4 col-centered">
        <h1>New Event.</h1>
        <%= form_for(@event) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control input-sm chat-input"%><br>

          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control input-sm chat-input"%><br>

          <%= f.label :date_time %>
          <%= f.datetime_field :date_time, class: "form-control input-sm chat-input" %><br>

          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control input-lg chat-input"%><br>


          <%= f.fields_for :attendees do |attendances_form| %>
            <%= attendances_form.label :attendees %>
            <%= attendances_form.text_field :names, placeholder: "Jonathan Lucy Fabienne", class: "form-control input-sm chat-input"%><br>
          <% end %>

          <%= f.submit "Submit", class: "btn btn-primary btn-md" %>

        <% end %>
      </div>
    </div>
</div>

app/views/events/show.html.erb
<div class="container" id="add-top-padding">
  <div class="row">
    <%= render 'layouts/event', :event => @event  %>
  </div>
</div>

app/views/layouts/_event.html.erb
	<div class="col-md-6 col-centered">
			<div class="panel">
        <div class="text-center">
          <div class="row">
            <div class="col-sm-9">
              <h3 class="pull-left"><%= link_to event.name, event %><a href="/users/<%=event.id%>"></a> </h3>
            </div>

						<!-- # => <a href="/users/1">Profile</a> -->


            <div class="col-sm-3">
              <h4 class="pull-right">
              <small><em><%= event.date_time.strftime("%B %d, %Y") if event.date_time %> <br> <%= event.date_time.strftime("%l %P") if event.date_time%></em></small>
              </h4>
            </div>
        </div>
    </div>
  <div class="panel-body">
      <span>Location: <b> <%= event.location %></b><span>
      <p> Created by: <b><%= event.creator.name.capitalize %></b>
      <br>Invited: <b>
      <% event.attendees.each_with_index do |a, i|  %>
        <% if a == event.attendees.last %>
          <%= "#{a.name.capitalize}." %>
        <% else %>
          <%= "#{a.name.capitalize}, "%>
        <% end %>
      <% end %></b>
      </p>
      <%= event.description %>
			<%= link_to "Delete", event, method: :delete if @current_user == event.creator %>
			<br><br><br><br>
  </div>
</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
      <div class="container">
        <%= link_to "Private Events", root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to "Create Event", new_event_url, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log Out", logout_url, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_url, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Log In", login_url, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">

      <!-- Bootstrap core CSS -->
      <link href="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

      <!-- Custom fonts for this template -->
      <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

      <!-- Custom styles for this template -->
      <link href="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/css/one-page-wonder.min.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <!-- <div id="flash" class="alert alert-success"> "hello"</div> -->
    <% flash.each do |message_type, message| %>
      <div id="flash" class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <script src="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/#vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-one-page-wonder/#vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </body>

</html>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>

<div class="row" id="add-top-padding">
  <div class="col-md-4 col-centered">
    <h1>New User.</h1>
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control input-sm chat-input"%><br>

      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control input-sm chat-input"%><br>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control input-sm chat-input"%><br>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control input-sm chat-input"%><br>

      <%= f.submit "Submit", class: "btn btn-primary btn-md" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="col-md-6 col-centered" id="add-top-padding">
      <div class="text-center">
      <h1><%= @user.name %></h1>
      <p><%= @user.email %></p>
      <h5><%= "#{@user.name}'s Events" %></h5>
    </div>
  </div>
</div>
<div class="container">
    <% @user.created_events.each do |event| %>
      <div class="row">
        <%= render 'layouts/event', :event => event  %>
      </div>
    <% end %>
</div>